# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: stronglytyped/arm-none-eabi-gcc:latest

pipelines:
  default:
    - step:
        script:
          # install deps
          - apt-get update && apt-get install -y mercurial
          - make
